import React,{useState} from "react";import{createRoot}from"react-dom/client";import"./style.css";
const initialEvents=[["Flame Dragon","Coming Soon","⚔️"],["Tyrant","Coming Soon","👑"],["Swordland","20 Sep 2026","🗡️"],["Alliance Brawl","Coming Soon","🏆"]];
const alliances=["LFA","HiddenLeaf","One Piece"];
function App(){
 const [page,setPage]=useState("Home"),[events,setEvents]=useState(initialEvents),[notice,setNotice]=useState("Welcome to Kingdom 602 — United We Stand."),[players,setPlayers]=useState([]),[form,setForm]=useState({name:"",alliance:"",power:""});
 const nav=["Home","Transfer","KVK","Events","Alliances","Players","Guides","Gallery","Announcements"];
 const addPlayer=e=>{e.preventDefault();if(form.name){setPlayers([...players,form]);setForm({name:"",alliance:"",power:""})}};
 return <div className="app"><header><div className="brand"><div className="crest">602</div><div><h1>KINGDOM 602</h1><p>United We Stand</p></div></div><button className="menu" onClick={()=>setPage(page==="Home"?"Events":"Home")}>☰</button></header>
 <nav>{nav.map(n=><button className={page===n?"active":""} onClick={()=>setPage(n)} key={n}>{n}</button>)}</nav>
 <main>
 {page==="Home"&&<><section className="hero"><span>WELCOME TO</span><h2>KINGDOM 602</h2><p>United We Stand</p><button onClick={()=>setPage("Transfer")}>ENTER TRANSFER CENTER →</button></section><section className="grid">{[["⚔️","KVK","Prepare. Fight. Unite.","KVK"],["🔄","TRANSFER","Join Kingdom 602","Transfer"],["📅","EVENTS","Kingdom event schedule","Events"],["👥","ALLIANCES","Our kingdom alliances","Alliances"]].map(x=><article onClick={()=>setPage(x[3])} className="card" key={x[1]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</section><section className="notice"><b>📢 Kingdom Announcement</b><p>{notice}</p></section></>}
 {page==="Transfer"&&<section className="panel"><h2>🔄 Transfer Center</h2><p>Apply to join Kingdom 602.</p><form onSubmit={e=>{e.preventDefault();alert("Application submitted! Admin review is required.");}}><input placeholder="Player name" required/><input placeholder="Current kingdom" required/><input placeholder="Power / TG level" required/><textarea placeholder="Tell us about yourself"></textarea><button>Submit Transfer Application</button></form></section>}
 {page==="KVK"&&<section className="panel"><h2>⚔️ KVK Center</h2><div className="kvk"><h3>Kingdom 602 KVK Command Center</h3><p>Save speedups, prepare troops, coordinate rallies and follow kingdom leadership announcements.</p><div className="grid"><div className="mini">Preparation<br/><strong>Coming Soon</strong></div><div className="mini">Battle Phase<br/><strong>Coming Soon</strong></div><div className="mini">Strategy<br/><strong>Team Coordination</strong></div></div></div></section>}
 {page==="Events"&&<section className="panel"><h2>📅 Kingdom Events</h2><div className="events">{events.map((e,i)=><div className="event" key={i}><span>{e[2]}</span><div><h3>{e[0]}</h3><p>{e[1]}</p></div></div>)}</div></section>}
 {page==="Alliances"&&<section className="panel"><h2>👥 Alliances</h2><div className="grid">{alliances.map(a=><div className="mini" key={a}><h3>{a}</h3><p>Alliance profile and recruitment information.</p></div>)}</div></section>}
 {page==="Players"&&<section className="panel"><h2>🧑 Player Directory</h2><form onSubmit={addPlayer} className="playerform"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Player name" required/><input value={form.alliance} onChange={e=>setForm({...form,alliance:e.target.value})} placeholder="Alliance"/><input value={form.power} onChange={e=>setForm({...form,power:e.target.value})} placeholder="Power"/><button>Add Player</button></form><div className="players">{players.length?players.map((p,i)=><div className="player" key={i}><b>{p.name}</b><span>{p.alliance||"No alliance"} • {p.power||"Power not listed"}</span></div>):<p>No players added yet.</p>}</div></section>}
 {page==="Guides"&&<section className="panel"><h2>📖 Guides</h2><div className="grid">{["KVK Preparation","Flame Dragon","Tyrant","Viking","Swordland","Alliance Strategy"].map(x=><div className="mini" key={x}><h3>{x}</h3><p>Guide content can be added from the admin system.</p></div>)}</div></section>}
 {page==="Gallery"&&<section className="panel"><h2>🖼️ Gallery</h2><div className="gallery"><div>602</div><div>⚔️</div><div>🏰</div><div>👑</div></div><p>Upload kingdom screenshots and event memories here in the next database version.</p></section>}
 {page==="Announcements"&&<section className="panel"><h2>📢 Announcements</h2><div className="notice"><p>{notice}</p></div><textarea value={notice} onChange={e=>setNotice(e.target.value)} placeholder="Update announcement (local preview)"></textarea></section>}
 </main><footer>© 2026 Kingdom 602 • United We Stand</footer></div>}
createRoot(document.getElementById("root")).render(<App/>);